### ISSUE TITLE
rubber sheets

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#271] opened 2018-12-03 18:09 UTC
rubber sheets (necessary for quest) can only be produced by the rolling machine in the early game. I would suggest to add an inefficent alloy smelter recipe and a more efficent extruder recipe (theres none either) like in GT5.

**Comment by Agrax** [comment] 2018-12-03 18:10
The issue is you can't even make rubber early game in the newest update you have :P But thanks, i'll look into that.

**Comment by Gamejet** [comment] 2018-12-03 18:12
god damn, I didnt even follow the recipe line that far. Is that gamebreaking?

**Comment by Agrax** [comment] 2018-12-03 18:13
Questline-breaking. Not game-breaking. It's just... nw. It'll be fixed in the next update

**Comment by Gamejet** [comment] 2018-12-03 18:17
yeah I see, you can make most LV-machines without the need for rubber. Still good to see it fixed next update :)

**Comment by Agrax** [comment] 2018-12-03 19:40
fixed via #270

**Comment by Agrax** [comment] 2019-01-07 00:16
Didn't fix it. Added rubber ingot recipe, but no rubber plate recipe. I have a design, so im gonna implement it shortly

**Comment by pyure** [comment] 2019-01-19 20:11
Done in infitech-prototype-0.35.zip

**Closed by pyure** 2019-01-19 20:11 UTC
Labels: Confirmed, Done in Dev, Tasked
