### ISSUE TITLE
Thaumcraft Plates

### ISSUE THREAD

**Issue by Arsonil** [pyure/infitech-prototype#263] opened 2018-12-01 19:29 UTC
The crafted Thaumcraft Plates do not work for the Thaumcraft Quest "Thaumium Essentia Smelter"
When crafted i got the pink ones for the quest i need the dark violet ones.

**Comment by Agrax** [comment] 2018-12-01 19:45
Is there a TC quest? O.o

**Comment by Agrax** [comment] 2018-12-01 19:49
You might be playing either a really outdated version or unlocked smth via /bq_admin

**Comment by Arsonil** [comment] 2018-12-01 20:03
i mean the quest in the thaumonomicon sry for this :P

**Comment by Agrax** [comment] 2018-12-01 20:05
Oh, that’s worse. Good to know. Thank you kindly for your feedback. It’ll be revised someday

**Comment by pyure** [comment] 2018-12-02 17:15
In the short term I believe we'll add a simple recipe to craft TC plates from GT plates.

**Comment by pyure** [comment] 2018-12-02 18:04
Not sure if it will help since I'm not sure how to reproduce the problem, but I've added a recipe to get TC plates from GT ones.

**Comment by pyure** [comment] 2018-12-06 13:53
Addressed in 0.34.

**Closed by pyure** 2018-12-06 13:53 UTC
Labels: Confirmed, Done in Dev, Tasked
