### ISSUE TITLE
Dynamite can't be crafted

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#166] opened 2018-10-07 20:51 UTC
![2018-10-07_15 47 46](https://user-images.githubusercontent.com/30029228/46586779-dda78700-ca48-11e8-8c81-7098682cf446.png)
That's what JEI shows, recipe doesn't work

**Comment by Agrax** [comment] 2018-10-07 23:29
Will probably be fixed in the next GA version. Caused by some weird GA-CT integration magical tricks

**Comment by pyure** [comment] 2018-10-14 05:10
Confirmed its due to Gregic Additions breaking crafttweaker (Again)

**Comment by pyure** [comment] 2018-10-18 02:04
infitech-prototype-0.23.zip

**Closed by pyure** 2018-10-18 02:04 UTC
Labels: Confirmed, Done in Dev, Tasked
