### ISSUE TITLE
High memory usage/memory leaks

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#447] opened 2019-03-31 13:10 UTC
Hello,

My friends and I are experiencing severe memory issues when the client is left running for too long.
With 6Gb allocated for the JVM at launch, the game runs fine for a while.
However at some point after about 1-2 hours of playing, the client gets to a point where it reaches its maximum allocated memory, launches the GC which freezes the client for about 5 seconds, but barely any memory is retrieved, so the GC is invoked again 5 seconds later, with the same effect.
This state isn't really playable, so we have to close and relaunch the client, which can be annoying since it takes a few minutes to start.

I realize this is a hard issue to fix, as it is likely spread across all the mods in the pack, however any progress in that regard will be greatly appreciated.

If there is anything I can provide that would be of use (world save, GC logs, memory profile captures, ...), please let me know.

**Comment by TLaviron** [comment] 2019-03-31 14:09
Update: it now takes me less than 45 minutes to reach this state.
Here is a GC log I have kept for this session. 
You can see right at the end that it goes Full GC every 10 seconds.
[GC.log](https://github.com/pyure/infitech-prototype/files/3026655/GC.log)

I fear this will only happen faster as our base grows more complex. 
I can't really increase the maximum memory size either; with the client actually using close to 10GB of system memory, the server running in parallel using another 2GB, plus the system and a bunch of other applications I have running at the same time, I am already dangerously close to using my 16Gb of RAM.

As I seem to be affected more by this than my friends, here is a list of things that I do more than them which _might_ be related to this issue:
- Looking up lots of different recipes in JEI (does JEI caches a lot of data?)
- Interacting with multiple different machines (does the machines GUI's get loaded when used, and never unloaded?)
- Crafting lots of different items in significant amounts, with all the components for new machines (I'm not sure how this would use a lot of memory, but who knows)

**Comment by pyure** [comment] 2019-03-31 14:13
I strongly suspect there's a gizmo in your base that is leaking memory.  Unfortunately I can't even speculate as to what it is.  We'll keep this ticket open and hopefully gather data over time.  If you get really desperate, you can try backing up your world and removing mods to see if any of that fixes the issue...notwithstanding the terribly long wait time.

Different java arguments that garbage-collect more aggressively might also work as a hack.  But this definitely looks like a specific leak since nobody else is running into it.

For your 3 points, you can probably cross off the first one: I spend many hours per session doing nothing but recipe work.

**Comment by TLaviron** [comment] 2019-03-31 20:52
Thanks for the feedback, I have indeed tried different GC options to see if it helped (it didn't), and I have tried getting a dump of the JVM memory to see what is going on.
No success so far, but I will keeping trying in this direction.

I'll let you know if I find anything useful/suspicious.

**Comment by pyure** [comment] 2019-04-06 12:02
I've updated the forestry mod, which was known to have resource leaks in our version.  I'll leave this ticket open for a while for following discussion after next IT3 release.

**Comment by TLaviron** [comment] 2019-04-06 16:43
Great, we'll try it when it comes out to see if it improves our issue.

On my end I just compared two heap dumps, the first right when after launching the client and connecting to the server, the second a while later when the client was starting to run out of memory.
Here's a summary of the first dump:
![heap_usage_login](https://user-images.githubusercontent.com/19927604/55672324-05fa2c00-589a-11e9-80a7-c5921d633420.png)
and here is a summary of the second:
![heap_usage_high](https://user-images.githubusercontent.com/19927604/55672329-13171b00-589a-11e9-90d4-89c1ff45c3d8.png)
It appears there is only one class responsible for leaking: "pl.asie.foamfix.common.PropertyValueMapper". The package name is unfamiliar to me, and the class name makes me wonder if it is an utility class that might be used by multiple mods, one one them using it wrongly.

I can't make much more out of those report myself, but if there's someone that could use the information in those dumps better, I will be happy to provide them

**Comment by pyure** [comment] 2019-04-06 16:49
Thanks TLaviron.  FoamFix by Asie is actually a performance-improving mod.  Its pretty common in modpacks these days.  And yes, its likely that a lot of logic traffic goes through it, so its not necessarily the culprit itself (as you've identified)

That said, when I updated Forestry I also updated Foamfix.

**Comment by TLaviron** [comment] 2019-04-07 15:32
I just tested with version 0.44 and the major leaks are still present, unfortunately.
I guess Forestry wasn't our culprit in this case.

**Comment by BorisMulder** [comment] 2019-04-16 17:05
I can confirm this on 0.45

**Comment by pyure** [comment] 2019-04-23 02:44
Just more info: Irongron has also encountered memory problems.  He may have isolated the problem to something like GT pipes across chunk boundaries.

**Comment by pyure** [comment] 2019-04-24 02:07
GT pipes wasn't the issue either.  Common element he identified was Iron Tanks from RC.  Which basically everyone uses because they're amazing.

**Comment by pyure** [comment] 2019-04-24 02:07
https://github.com/Railcraft/Railcraft/issues/1823

**Comment by TLaviron** [comment] 2019-04-25 20:34
I just tested with an iron tank and not much else (a few gregtech pipes, a nuclear craft water generator and some buildcraft void fluid pipes), and could reproduce the leaks. 
However, I tried removing foamfix to see if I could get more info, but without it, the same world shows no sign of memory leak.

It also seems the railcraft steel tank has no leak issues, though I need to test some more to confirm.

I'll see If I can really narrow it to the railcraft iron tank/foamfix combination

**Comment by pyure** [comment] 2019-04-25 20:36
TLaviron, would you be able to extract another core dump similar to above when you narrow it down?   Liach specifically requested one.

**Comment by TLaviron** [comment] 2019-04-26 16:39
I am working on it, and will forward it to the railcraft devs when it's ready.

**Comment by TLaviron** [comment] 2019-04-28 21:43
After further testing, it looks the steel tank has the same memory issue as the iron tank.

As a temporary workaround, we have disabled foamfix on the client (the server still loads it), and we have been able to play uninterrupted for several hours. We loose whatever performance improvements foamfix brings, but it has been acceptable on our case, so if anyone has the same issue, consider doing the same until a fix is released.

**Comment by pyure** [comment] 2019-04-28 21:47
This is excellent information, thanks

**Comment by pyure** [comment] 2019-05-23 02:12
Latest update from liach (RC dev) is that he's going to do a thing that involves stuff.  Its all over my head.  Fingers crossed.

**Comment by pyure** [comment] 2019-07-06 22:50
I'm closing this as we have adopted the same workaround in the modpack itself (removing foamfix)

I'm still monitoring the RC side of the issue itself periodically.  We also believe it is safe for the Server to run foamfix, as the memory leaks tied to graphics/models concerns client-side optimizations specifically.

Addressed in 1.0.6

**Closed by pyure** 2019-07-06 22:50 UTC
Labels: Need Info, help wanted
