### ISSUE TITLE
Gregtech cables and pipes only work on one side

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#274] opened 2018-12-03 23:45 UTC
GT-cables (and pipes) can only transport energy (liquid) threw one side. If theres a split in two directions only the side where the cable (pipe) got hooked on first will transport energy (liquid).

not working:
![2018-12-04_00 37 39](https://user-images.githubusercontent.com/9951856/49408719-bc6bca00-f75d-11e8-8dc0-e9741bee0afb.png)
working:
![2018-12-04_00 38 40](https://user-images.githubusercontent.com/9951856/49408723-bf66ba80-f75d-11e8-9607-0021d38766f3.png)

**Comment by pyure** [comment] 2018-12-04 00:32
Is it only "dead" because the other directions take priority?  In other words, does the dead machine receive energy once the other two buffers are filled?

**Comment by pyure** [comment] 2018-12-04 00:38
![image](https://user-images.githubusercontent.com/8617528/49410520-02f7ff00-f733-11e8-87c9-86f795756877.png)

**Comment by pyure** [comment] 2018-12-04 00:38
All three of these are getting power for me, via a 1x tin cable from a steam turbine.

**Comment by Gamejet** [comment] 2018-12-04 00:48
okay, thats really weird. And no buffers ran full before, I tested it five times on my server.

**Comment by pyure** [comment] 2018-12-04 00:49
"no" buffers?  If some machines were receiving power they should have filled buffers.

Can you try to reproduce again on your side?  If it fails, can you try single player instead of server?

**Comment by Gamejet** [comment] 2018-12-04 01:02
As I said there were buffers on the other two machine and they both ran full. Only the last machine wouldnt receive energy and I had to deal with the same issue when I used bronze fluid pipes.
However, I wasnt able to reproduce this issue. Its really weird because as you can see in the picture my setup was right. It seems like this is only happens under certain circumstances.

**Comment by pyure** [comment] 2018-12-04 01:05
Hm.  We'll close the issue for now but I'll try to bear it in mind if/when it crops up again.

**Closed by pyure** 2018-12-04 01:05 UTC
Labels: Bounced to Mod Dev, Cannot reproduce
