### ISSUE TITLE
Mechanical drying basin + methane

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#471] opened 2019-04-07 21:19 UTC
The recipe should take 8 and produce 30mB? Or 240mb?

Instead it takes 1 pulped biomass and produces 240mB of methane.

Broken af. Can be abused to make A LOT of methane (1/4 of a bucket per pulped biomass) You get ca. 2 per centrifuge run. Abusable pretty quickly

**Comment by pyure** [comment] 2019-04-11 00:41
![image](https://user-images.githubusercontent.com/8617528/55922820-ea13c480-5bd0-11e9-8621-1f9106ff1f1e.png)
Seems to be a bug with the mod.  JEI reports the correct recipe, but I can reproduce the 1-pulped biomass input as indicated.  For now, I'll make it run "faster" rather than in bulk.

**Comment by pyure** [comment] 2019-04-11 01:34
Updated mod to latest version.  Temporarily removed the regular drying basin version to test if there was some sort of weird conflict (nope).

https://github.com/CyclopsMC/IntegratedDynamics/issues/716

**Comment by pyure** [comment] 2019-04-12 03:08
Fixed in infitech-prototype-0.45
Dev is aware of issue and will fix CT on his side.  We may revisit this pending that fix and redo this recipe as a Bulk version again.

**Closed by pyure** 2019-04-12 03:08 UTC
Labels: Done in Dev
