### ISSUE TITLE
EBF silicone recipe bugs

### ISSUE THREAD

**Issue by Ligi89** [pyure/infitech-prototype#475] opened 2019-04-11 08:37 UTC
The EBF consumes the integrated circuit when baking a silicone ingot from silicon dust.

Also, I can't make a silicon boule in EBF, as it just makes silicon ingot and consumes the circuit too,  no matter the configuration it's set to, it seems.

**Comment by Agrax** [comment] 2019-04-11 13:58
Can't reproduce neither of those, but im runnin the newest version (.387), whereas the pack has yet to update

**Comment by pyure** [comment] 2019-04-11 23:14
Confirmed, seems fine in newest version.  Will close upon update.

**Comment by pyure** [comment] 2019-04-12 03:07
Fixed in infitech-prototype-0.45

**Closed by pyure** 2019-04-12 03:07 UTC
Labels: Fixed by Mod Dev
