### ISSUE TITLE
Iron doors allow for easy iron duplication.

### ISSUE THREAD

**Issue by Earthyx** [pyure/infitech-prototype#285] opened 2018-12-12 20:15 UTC
Recipe takes 6 iron plates and creates 3 doors. Each door macerated creates 6 iron dust. Recipe needs adjustment

**Comment by Agrax** [comment] 2018-12-12 23:21
It might be already fixed on GA side. Im not certain, but the issue is known to me

**Comment by pyure** [comment] 2019-01-19 20:49
Apparently fixed in a recent version of GT-CE.  When GA updates we can move to that version.

**Comment by pyure** [comment] 2019-02-07 03:16
Released in infitech-prototype-0.36.zip

**Closed by pyure** 2019-02-07 03:16 UTC
Labels: Confirmed, Fixed by Mod Dev, Known Issue
