### ISSUE TITLE
Quest 'better steam storage' requires unused bronze tank

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#386] opened 2019-03-20 19:34 UTC
Hello,

I had a bronze tank full of steam before the quest was available for completion.
When i tried picking it up, even after emptying it, it would not complete the quest.
Crafting a new one worked.

Also, the 'used' and new tank do not stack, although multiple new tanks do (probably for the same reason):
![2019-03-20_20 26 53](https://user-images.githubusercontent.com/19927604/54713670-77727480-4b4f-11e9-8a9e-5e09d5d480e3.png)

**Comment by pyure** [comment] 2019-03-21 00:16
Thanks TLaviron. I couldn't reproduce the emptying behaviour.  When I filled it with steam and picked it up, no quest triggered (not ideal).  But when I emptied it with a bucket and picked it up, the quest triggered properly.  

Its possible you used a different method to empty the tank which left some nbt attached?

That said, I've tweaked the quest so that its no longer interested in nbt at all, and liquids won't stop the tank from being recognized.

**Comment by TLaviron** [comment] 2019-03-21 17:41
Hi pyure, 

You guessed right, I used a different way  to empty the tank: I emptied it into a Fancy Fluid storage tank, and there was indeed some nbt still attached.

I put some steam back in the fluid tank and emptied it with a bucket and it correctly removed the tag.
Thanks for quick reply.

**Comment by pyure** [comment] 2019-03-21 17:47
Your bug finds are helping us refine the quality of the modpack.  Keep it up :)

**Comment by pyure** [comment] 2019-03-21 23:19
Fixed in 0.41

**Closed by pyure** 2019-03-21 23:19 UTC
Labels: Done in Dev
