### ISSUE TITLE
gregtech pipe covers never block flow between pipes?

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#409] opened 2019-03-24 18:38 UTC
Hello, 

While I was trying to figure out a way to prevent steam produced by boilers going into the water-providing pipe, I found out that placing covers such as pumps or fluid filters between pipes did not stop liquid from flowing. Here's a screenshot of my experiment:
![2019-03-24_19 13 56](https://user-images.githubusercontent.com/19927604/54883891-dc3d1000-4e6a-11e9-9a58-8cd4bfec1428.png)
From bottom to top, I placed pairs of pumps in export mode, pumps in import mode, fluid filters without any fluids allowed and fluid filters with a dummy (liquid aluminium) fluid allowed. Water comes from the right (all fluid filters are on filter fill mode).

Connecting the holes with pipes, all the tanks fill up:
![2019-03-24_19 16 30](https://user-images.githubusercontent.com/19927604/54883959-78671700-4e6b-11e9-9b09-aad3283bca0f.png)

(not in picture: shutter modules did not prevent water from flowing either)
Is this the expected behavior? I remember from playing Infitech 2 that you could cut off fluid flow in one way with covers, but I don't know if pipes in GTCE are supposed to do the same.

PS: if I replace the connecting pipes with fluid tanks, I get the behavior I expected:
![2019-03-24_19 14 59](https://user-images.githubusercontent.com/19927604/54884032-46a28000-4e6c-11e9-9046-95f122402434.png)
Since this is the use case that matches what I was trying to do in the first place, this would be good enough for me for the moment.

**Comment by Agrax** [comment] 2019-03-27 17:08
In *theory* FMP (forge multipart) should cut off the flow. In practice there's nothing that can prevent liquids from flowing. The issue with FMP is... complex tho. The mod hasn't been updated in a while and this multipart API is a bit outdated. Arch is gonna migrate to MCMultiPart, but it takes time and he's the only one to actively work on GTCE. Technically MCMP should work better, cut off the flow as expected and allow to use Chisel and Bits as covers

**Comment by TLaviron** [comment] 2019-03-31 21:00
Thanks for the reply.
I was a bit surprised with the current behavior, but it's not game braking (covers between machines and pipes _do_ work).
I'll just have to keep that in mind when designing pipe networks.

**Comment by Agrax** [comment] 2019-05-19 01:29
I *think* the issue is no more existant. Check and close

**Comment by pyure** [comment] 2019-06-29 15:33
Apparently addressed by Archengius.

**Comment by pyure** [comment] 2019-06-29 16:15
Addressed in 1.0.5

**Closed by pyure** 2019-06-29 16:15 UTC
Labels: Bounced to Mod Dev, Fixed by Mod Dev
